services:
  
  nginx:
    image: nginx:alpine
    ports: 
      - "80:80"
    volumes: 
      - ./nginx/canvas.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    restart: unless-stopped

  web:
    build:
      context: ./canvas-lms
      dockerfile: Dockerfile
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    environment:
      #Este se debe modificar cuando nos vayamos a prod
      RAILS_ENV: development
      CANVAS_LMS_ADMIN_EMAIL: antonio.biorivera@gmail.com
      CANVAS_LMS_ADMIN_PASSWORD: mang00la123
      CANVAS_LMS_ACCOUNT_NAME: "UAEMEX"
    volumes:
      - ./canvas-lms:/usr/src/app
      - canvas_node_modules:/usr/src/app/node_modules
      - canvas_packs:/usr/src/app/public/packs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped 


  jobs:
    build:
      context: ./canvas-lms
      dockerfile: Dockerfile
    command: bundle exec script/delayed_job run
    environment:
      RAILS_ENV: development
    volumes:
      - ./canvas-lms:/usr/src/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  rce:
    image: instructure/canvas-rce-api
    environment:
      PORT: 3001
    restart: unless-stopped

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: canvas_development
      POSTGRES_USER: canvas
      POSTGRES_PASSWORD: mang00la123
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "canvas"]
      interval: 5s
      timeout: 5s 
      retries: 10
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    volumes: 
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
  canvas_node_modules:
  canvas_packs:

