upstream canvas {
	server web:3000;
}

upstream rce {
	server rce:80;
}

server {
	listen 80;
	server_name localhost;

	client_max_body_size 500M;

	# Proxy RCE API requests
	location /rce/ {
	  proxy_pass         http://rce/;
          proxy_set_header   Host              $http_host;
          proxy_set_header   X-Real-IP         $remote_addr;
          proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
          proxy_set_header   X-Forwarded-Proto $scheme;
          proxy_read_timeout    300;
          proxy_connect_timeout 300;
          proxy_send_timeout    300;
          proxy_buffering    off;
	}

	# Proxy Canvas requests
	location / {
	  proxy_pass         http://canvas;
          proxy_set_header   Host              $http_host;
          proxy_set_header   X-Real-IP         $remote_addr;
          proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
          proxy_set_header   X-Forwarded-Proto $scheme;
          proxy_read_timeout    300;
          proxy_connect_timeout 300;
          proxy_send_timeout    300;
          proxy_buffering    off;
	}

}
